//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagerDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Task_Id { get; set; }
        public string Task_Name { get; set; }
        public int Project_Id { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public int Priority { get; set; }
        public bool Staus { get; set; }
        public string Parent_Name { get; set; }
        public string Project_Name { get; set; }

        public virtual Parent_Task Parent_Task { get; set; }
        public virtual Project Project { get; set; }
    }
}
